=== cul-it/cular-metadata/manifest_schema_storage.json
{
    "$id": "https://github.com/cul-it/cular-metadata/blob/main/manifest_schema_storage.json",
    "$schema": "http://json-schema.org/draft-06/schema#",
    "type": "object",
    "properties": {
        "collection_id": {
            "type": "string"
        },
        "depositor": {
            "type": "string"
        },
        "steward": {
            "type": "string",
            "pattern": "^[a-zA-Z]{1,4}[0-9]{1,6}$"
        },
        "documentation": {
            "type": "string",
            "minLength": 2
        },
        "packages": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/package"
            }
        },
        "number_packages": {
            "type": "integer"
        }
    },
    "required": [
        "collection_id",
        "depositor",
        "documentation",
        "packages",
        "number_packages"
    ],
    "additionalProperties": false,
    "definitions": {
        "package": {
            "type": "object",
            "properties": {
                "package_id": {
                    "type": "string",
                    "pattern": "^urn:uuid:[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
                },
                "bibid": {
                    "type": "string"
                },
                "local_id": {
                    "type": "string"
                },
                "files": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/file"
                    }
                },
                "number_files": {
                    "type": "integer"
                }
            },
            "required": [
                "package_id",
                "files",
                "number_files"
            ],
            "additionalProperties": false
        },
        "file": {
            "type": "object",
            "properties": {
                "filepath": {
                    "type": "string"
                },
                "sha1": {
                    "type": "string",
                    "pattern": "^[0-9a-f]{40}$"
                },
                "md5": {
                    "type": "string",
                    "pattern": "^[0-9a-f]{32}$"
                },
                "size": {
                    "type": "integer"
                },
                "ingest_date": {
                    "type": "string",
                    "pattern": "^[0-9-]{10}$"
                },
                "tool_version": {
                    "type": "string"
                },
                "media_type": {
                    "type": "string"
                }
            },
            "required": [
                "filepath",
                "sha1",
                "size",
                "ingest_date",
                "tool_version",
                "media_type"
            ],
            "additionalProperties": false
        }
    }
}

=== cul-it/cular-metadata/examples/_EM_Depositor_Collection_Name.json
{
  "depositor": "Depositor",
  "collection_id": "CULAR_Colllection_ID",
  "steward": "net272",
  "documentation": "urn:uuid:621d27a2-c673-40ef-9bc2-875de042d7d6",
  "number_packages": 2,
  "packages": [
    {
      "package_id": "urn:uuid:621d27a2-c673-40ef-9bc2-875de042d7d6",
      "number_files": 3,
      "files": [
        {
          "filepath": "_Documentation/CollectionEAD.xml",
          "sha1": "55df863aed837d8e97661a6a8343dcfe8d668150",
          "size": 29217,
          "ingest_date": "2026-01-28",
          "tool_version": "Apache Tika 2.9.2",
          "media_type": "application/xml"
        },
        {
          "filepath": "_Documentation/PreIngest_Report_CollectionName.pdf",
          "sha1": "616bab2446420cbe579d819564472bdc6cd8af32",
          "size": 186676,
          "ingest_date": "2026-01-28",
          "tool_version": "Apache Tika 2.9.2",
          "media_type": "application/pdf"
        },
        {
          "filepath": "_Documentation/CollectionNumber_ReadMe_Digitization_Specs.txt",
          "sha1": "c49970f1f001d523a21213f651768afe2c6ae0b9",
          "size": 5681,
          "ingest_date": "2026-01-28",
          "tool_version": "Apache Tika 2.9.2",
          "media_type": "text/plain"
        }
      ]
    },
    {
      "package_id": "urn:uuid:4138928d-34ab-4867-9590-61651b798371",
      "local_id": "LocalID",
      "number_files": 4,
      "files": [
        {
          "filepath": "CollectionName_LocalID/CollectionName_LocalID_mkv_exiftool.xml",
          "sha1": "d9e98abce1bef7b839c9331c2dfae7f236debe8d",
          "size": 2837,
          "ingest_date": "2026-01-28",
          "tool_version": "Apache Tika 2.9.2",
          "media_type": "application/rdf+xml"
        },
        {
          "filepath": "CollectionName_LocalID/CollectionName_LocalID_mp4_exiftool.xml",
          "sha1": "8311f1de8d2a2a25ae5fb27d19a851142bf45af1",
          "size": 8033,
          "ingest_date": "2026-01-28",
          "tool_version": "Apache Tika 2.9.2",
          "media_type": "application/rdf+xml"
        },
        {
          "filepath": "CollectionName_LocalID/CollectionName_LocalID.mkv",
          "sha1": "dc2701bb053d3ea3777623268a35c06462b27e1c",
          "size": 66822203,
          "ingest_date": "2026-01-28",
          "tool_version": "Apache Tika 2.9.2",
          "media_type": "video/x-matroska"
        },
        {
          "filepath": "CollectionName_LocalID/CollectionName_LocalID.mp4",
          "sha1": "7108faaf4bb78bf1a69818041a7c56a3d66e2068",
          "size": 11030173,
          "ingest_date": "2026-01-28",
          "tool_version": "Apache Tika 2.9.2",
          "media_type": "video/mp4"
        }
      ]
    }
  ]
}

=== cul-it/cular-metadata/manifest_storage.json
{
  "collection_id": "EXAMPLE_COLLECTION_1",
  "depositor": "DEPOSITOR",
  "steward": "net272",
  "documentation": "urn:uuid:a036a6c0-3038-4bee-a6b6-b80c7a7858ff",
  "number_packages": 1,
  "packages": [
    {
      "package_id": "urn:uuid:f81d4fae-7dec-11d0-a765-00a0c91e6bf6",
      "bibid": "123456",
      "local_id": "31924",
      "number_files": 2,
      "files": [
        {
          "filepath": "a_file",
          "sha1": "058bbd836dfc8e22d57d5dc8c048f15d8aed7dc4",
          "md5": "61a6104561744087fe62e7878948d9b7",
          "size": 12,
          "ingest_date": "2020-08-13",
          "tool_version": "tika-2.1.0",
          "media_type": "text/plain" 
        },
        {
          "filepath": "foo/bar.xml",
          "sha1": "2c789aee68c6803b0a45f1627a368a0af9785223",
          "md5": "5f859ade8cffd1a94543f4f660ab1b99",
          "size": 68,
          "ingest_date": "2020-03-16",
          "tool_version": "tika-2.1.0",
          "media_type": "text/xml"
        }
      ]
    }
  ]
}
